// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: rosco.proto

package rosco

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusTopic int32

const (
	BusTopic_ROSCO_EVENT   BusTopic = 0
	BusTopic_ROSCO_REQUEST BusTopic = 1
	BusTopic_ROSCO_COMMAND BusTopic = 2
)

// Enum value maps for BusTopic.
var (
	BusTopic_name = map[int32]string{
		0: "ROSCO_EVENT",
		1: "ROSCO_REQUEST",
		2: "ROSCO_COMMAND",
	}
	BusTopic_value = map[string]int32{
		"ROSCO_EVENT":   0,
		"ROSCO_REQUEST": 1,
		"ROSCO_COMMAND": 2,
	}
)

func (x BusTopic) Enum() *BusTopic {
	p := new(BusTopic)
	*p = x
	return p
}

func (x BusTopic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusTopic) Descriptor() protoreflect.EnumDescriptor {
	return file_rosco_proto_enumTypes[0].Descriptor()
}

func (BusTopic) Type() protoreflect.EnumType {
	return &file_rosco_proto_enumTypes[0]
}

func (x BusTopic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusTopic.Descriptor instead.
func (BusTopic) EnumDescriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{0}
}

type MessageTypeRequest int32

const (
	MessageTypeRequest_CONFIG_GET_REQ    MessageTypeRequest = 0
	MessageTypeRequest_CONFIG_GET_RESP   MessageTypeRequest = 1
	MessageTypeRequest_MESSAGE_SEND_REQ  MessageTypeRequest = 2
	MessageTypeRequest_MESSAGE_SEND_RESP MessageTypeRequest = 3
	MessageTypeRequest_SCRIPT_RUN_REQ    MessageTypeRequest = 4
	MessageTypeRequest_SCRIPT_RUN_RESP   MessageTypeRequest = 5
)

// Enum value maps for MessageTypeRequest.
var (
	MessageTypeRequest_name = map[int32]string{
		0: "CONFIG_GET_REQ",
		1: "CONFIG_GET_RESP",
		2: "MESSAGE_SEND_REQ",
		3: "MESSAGE_SEND_RESP",
		4: "SCRIPT_RUN_REQ",
		5: "SCRIPT_RUN_RESP",
	}
	MessageTypeRequest_value = map[string]int32{
		"CONFIG_GET_REQ":    0,
		"CONFIG_GET_RESP":   1,
		"MESSAGE_SEND_REQ":  2,
		"MESSAGE_SEND_RESP": 3,
		"SCRIPT_RUN_REQ":    4,
		"SCRIPT_RUN_RESP":   5,
	}
)

func (x MessageTypeRequest) Enum() *MessageTypeRequest {
	p := new(MessageTypeRequest)
	*p = x
	return p
}

func (x MessageTypeRequest) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageTypeRequest) Descriptor() protoreflect.EnumDescriptor {
	return file_rosco_proto_enumTypes[1].Descriptor()
}

func (MessageTypeRequest) Type() protoreflect.EnumType {
	return &file_rosco_proto_enumTypes[1]
}

func (x MessageTypeRequest) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageTypeRequest.Descriptor instead.
func (MessageTypeRequest) EnumDescriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{1}
}

type MessageTypeCommand int32

const (
	MessageTypeCommand_CONFIG_SET_REQ  MessageTypeCommand = 0
	MessageTypeCommand_CONFIG_SET_RESP MessageTypeCommand = 1
)

// Enum value maps for MessageTypeCommand.
var (
	MessageTypeCommand_name = map[int32]string{
		0: "CONFIG_SET_REQ",
		1: "CONFIG_SET_RESP",
	}
	MessageTypeCommand_value = map[string]int32{
		"CONFIG_SET_REQ":  0,
		"CONFIG_SET_RESP": 1,
	}
)

func (x MessageTypeCommand) Enum() *MessageTypeCommand {
	p := new(MessageTypeCommand)
	*p = x
	return p
}

func (x MessageTypeCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageTypeCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_rosco_proto_enumTypes[2].Descriptor()
}

func (MessageTypeCommand) Type() protoreflect.EnumType {
	return &file_rosco_proto_enumTypes[2]
}

func (x MessageTypeCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageTypeCommand.Descriptor instead.
func (MessageTypeCommand) EnumDescriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{2}
}

type ScriptActionType int32

const (
	ScriptActionType_ActionTypeSet   ScriptActionType = 0
	ScriptActionType_ActionTypeFade  ScriptActionType = 1
	ScriptActionType_ActionTypeSleep ScriptActionType = 2
)

// Enum value maps for ScriptActionType.
var (
	ScriptActionType_name = map[int32]string{
		0: "ActionTypeSet",
		1: "ActionTypeFade",
		2: "ActionTypeSleep",
	}
	ScriptActionType_value = map[string]int32{
		"ActionTypeSet":   0,
		"ActionTypeFade":  1,
		"ActionTypeSleep": 2,
	}
)

func (x ScriptActionType) Enum() *ScriptActionType {
	p := new(ScriptActionType)
	*p = x
	return p
}

func (x ScriptActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScriptActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_rosco_proto_enumTypes[3].Descriptor()
}

func (ScriptActionType) Type() protoreflect.EnumType {
	return &file_rosco_proto_enumTypes[3]
}

func (x ScriptActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScriptActionType.Descriptor instead.
func (ScriptActionType) EnumDescriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{3}
}

type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port    uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Target) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Target) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets map[int32]*Target `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Scripts map[int32]*Script `protobuf:"bytes,2,rep,name=scripts,proto3" json:"scripts,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetTargets() map[int32]*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Config) GetScripts() map[int32]*Script {
	if x != nil {
		return x.Scripts
	}
	return nil
}

type ConfigGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigGetRequest) Reset() {
	*x = ConfigGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetRequest) ProtoMessage() {}

func (x *ConfigGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetRequest.ProtoReflect.Descriptor instead.
func (*ConfigGetRequest) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{2}
}

type ConfigGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ConfigGetResponse) Reset() {
	*x = ConfigGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetResponse) ProtoMessage() {}

func (x *ConfigGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetResponse.ProtoReflect.Descriptor instead.
func (*ConfigGetResponse) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigGetResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type OSCValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*OSCValue_Nil
	//	*OSCValue_Int32
	//	*OSCValue_Float32
	//	*OSCValue_String_
	//	*OSCValue_Blob
	//	*OSCValue_Int64
	//	*OSCValue_True
	//	*OSCValue_False
	Value isOSCValue_Value `protobuf_oneof:"value"`
}

func (x *OSCValue) Reset() {
	*x = OSCValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSCValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSCValue) ProtoMessage() {}

func (x *OSCValue) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSCValue.ProtoReflect.Descriptor instead.
func (*OSCValue) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{4}
}

func (m *OSCValue) GetValue() isOSCValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *OSCValue) GetNil() int32 {
	if x, ok := x.GetValue().(*OSCValue_Nil); ok {
		return x.Nil
	}
	return 0
}

func (x *OSCValue) GetInt32() int32 {
	if x, ok := x.GetValue().(*OSCValue_Int32); ok {
		return x.Int32
	}
	return 0
}

func (x *OSCValue) GetFloat32() float32 {
	if x, ok := x.GetValue().(*OSCValue_Float32); ok {
		return x.Float32
	}
	return 0
}

func (x *OSCValue) GetString_() string {
	if x, ok := x.GetValue().(*OSCValue_String_); ok {
		return x.String_
	}
	return ""
}

func (x *OSCValue) GetBlob() []byte {
	if x, ok := x.GetValue().(*OSCValue_Blob); ok {
		return x.Blob
	}
	return nil
}

func (x *OSCValue) GetInt64() int64 {
	if x, ok := x.GetValue().(*OSCValue_Int64); ok {
		return x.Int64
	}
	return 0
}

func (x *OSCValue) GetTrue() bool {
	if x, ok := x.GetValue().(*OSCValue_True); ok {
		return x.True
	}
	return false
}

func (x *OSCValue) GetFalse() bool {
	if x, ok := x.GetValue().(*OSCValue_False); ok {
		return x.False
	}
	return false
}

type isOSCValue_Value interface {
	isOSCValue_Value()
}

type OSCValue_Nil struct {
	Nil int32 `protobuf:"varint,1,opt,name=nil,proto3,oneof"`
}

type OSCValue_Int32 struct {
	Int32 int32 `protobuf:"varint,2,opt,name=int32,proto3,oneof"`
}

type OSCValue_Float32 struct {
	Float32 float32 `protobuf:"fixed32,3,opt,name=float32,proto3,oneof"`
}

type OSCValue_String_ struct {
	String_ string `protobuf:"bytes,4,opt,name=string,proto3,oneof"`
}

type OSCValue_Blob struct {
	Blob []byte `protobuf:"bytes,5,opt,name=blob,proto3,oneof"`
}

type OSCValue_Int64 struct {
	Int64 int64 `protobuf:"varint,6,opt,name=int64,proto3,oneof"`
}

type OSCValue_True struct {
	// int64    time     = 7;
	// int64    double   = 8;
	True bool `protobuf:"varint,9,opt,name=true,proto3,oneof"`
}

type OSCValue_False struct {
	False bool `protobuf:"varint,10,opt,name=false,proto3,oneof"`
}

func (*OSCValue_Nil) isOSCValue_Value() {}

func (*OSCValue_Int32) isOSCValue_Value() {}

func (*OSCValue_Float32) isOSCValue_Value() {}

func (*OSCValue_String_) isOSCValue_Value() {}

func (*OSCValue_Blob) isOSCValue_Value() {}

func (*OSCValue_Int64) isOSCValue_Value() {}

func (*OSCValue_True) isOSCValue_Value() {}

func (*OSCValue_False) isOSCValue_Value() {}

type SendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target  int32       `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Address string      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Values  []*OSCValue `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageRequest) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *SendMessageRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SendMessageRequest) GetValues() []*OSCValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{6}
}

type ConfigSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ConfigSetRequest) Reset() {
	*x = ConfigSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSetRequest) ProtoMessage() {}

func (x *ConfigSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSetRequest.ProtoReflect.Descriptor instead.
func (*ConfigSetRequest) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigSetRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ConfigSetResponse) Reset() {
	*x = ConfigSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSetResponse) ProtoMessage() {}

func (x *ConfigSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSetResponse.ProtoReflect.Descriptor instead.
func (*ConfigSetResponse) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigSetResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type ScriptAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       ScriptActionType `protobuf:"varint,1,opt,name=type,proto3,enum=rosco.ScriptActionType" json:"type,omitempty"`
	Address    string           `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Values     []*OSCValue      `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	DurationMs uint32           `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
}

func (x *ScriptAction) Reset() {
	*x = ScriptAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptAction) ProtoMessage() {}

func (x *ScriptAction) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptAction.ProtoReflect.Descriptor instead.
func (*ScriptAction) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{9}
}

func (x *ScriptAction) GetType() ScriptActionType {
	if x != nil {
		return x.Type
	}
	return ScriptActionType_ActionTypeSet
}

func (x *ScriptAction) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ScriptAction) GetValues() []*OSCValue {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ScriptAction) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Script struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Actions []*ScriptAction `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *Script) Reset() {
	*x = Script{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Script) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Script) ProtoMessage() {}

func (x *Script) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Script.ProtoReflect.Descriptor instead.
func (*Script) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{10}
}

func (x *Script) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Script) GetActions() []*ScriptAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ScriptRunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target   int32   `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Script   *Script `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	ScriptId int32   `protobuf:"varint,3,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
}

func (x *ScriptRunRequest) Reset() {
	*x = ScriptRunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptRunRequest) ProtoMessage() {}

func (x *ScriptRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptRunRequest.ProtoReflect.Descriptor instead.
func (*ScriptRunRequest) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{11}
}

func (x *ScriptRunRequest) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *ScriptRunRequest) GetScript() *Script {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *ScriptRunRequest) GetScriptId() int32 {
	if x != nil {
		return x.ScriptId
	}
	return 0
}

type ScriptRunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScriptRunResponse) Reset() {
	*x = ScriptRunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosco_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptRunResponse) ProtoMessage() {}

func (x *ScriptRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rosco_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptRunResponse.ProtoReflect.Descriptor instead.
func (*ScriptRunResponse) Descriptor() ([]byte, []int) {
	return file_rosco_proto_rawDescGZIP(), []int{12}
}

var File_rosco_proto protoreflect.FileDescriptor

var file_rosco_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x6f, 0x73, 0x63, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72,
	0x6f, 0x73, 0x63, 0x6f, 0x22, 0x4a, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0x8a, 0x02, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x34, 0x0a, 0x07, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72,
	0x6f, 0x73, 0x63, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x73, 0x12, 0x34, 0x0a, 0x07, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x6f, 0x73, 0x63, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x1a, 0x49, 0x0a, 0x0c, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f, 0x73, 0x63, 0x6f,
	0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x1a, 0x49, 0x0a, 0x0c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f, 0x73, 0x63, 0x6f, 0x2e, 0x53, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x12, 0x0a,
	0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3a, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f, 0x73, 0x63, 0x6f, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xd1, 0x01,
	0x0a, 0x08, 0x4f, 0x53, 0x43, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x6e, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x03, 0x6e, 0x69, 0x6c, 0x12, 0x16,
	0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x1a, 0x0a, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33,
	0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x33, 0x32, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x04,
	0x62, 0x6c, 0x6f, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6c,
	0x6f, 0x62, 0x12, 0x16, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x72,
	0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x74, 0x72, 0x75, 0x65,
	0x12, 0x16, 0x0a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x6f, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x27, 0x0a, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x6f, 0x73, 0x63,
	0x6f, 0x2e, 0x4f, 0x53, 0x43, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x10, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x72, 0x6f, 0x73, 0x63, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x22, 0x3a, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f, 0x73, 0x63,
	0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x22, 0x9f, 0x01, 0x0a, 0x0c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x72, 0x6f, 0x73, 0x63, 0x6f, 0x2e, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x27, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x6f, 0x73, 0x63, 0x6f,
	0x2e, 0x4f, 0x53, 0x43, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x73, 0x22, 0x4b, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2d, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x72, 0x6f, 0x73, 0x63, 0x6f, 0x2e, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x6e, 0x0a, 0x10, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f,
	0x73, 0x63, 0x6f, 0x2e, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x06, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x49, 0x64, 0x22,
	0x13, 0x0a, 0x11, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x41, 0x0a, 0x08, 0x42, 0x75, 0x73, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x53, 0x43, 0x4f, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x4f, 0x53, 0x43, 0x4f, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x4f, 0x53, 0x43, 0x4f, 0x5f, 0x43, 0x4f,
	0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x10, 0x02, 0x2a, 0x93, 0x01, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x0e, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x51,
	0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x47, 0x45, 0x54,
	0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x02, 0x12, 0x15, 0x0a,
	0x11, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45,
	0x53, 0x50, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x5f, 0x52,
	0x55, 0x4e, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x43, 0x52, 0x49,
	0x50, 0x54, 0x5f, 0x52, 0x55, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x05, 0x2a, 0x3d, 0x0a,
	0x12, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x53, 0x45,
	0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x4e, 0x46, 0x49,
	0x47, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x01, 0x2a, 0x4e, 0x0a, 0x10,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x11, 0x0a, 0x0d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x53, 0x65,
	0x74, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x46, 0x61, 0x64, 0x65, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x10, 0x02, 0x42, 0x20, 0x5a, 0x1e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6e,
	0x6f, 0x6d, 0x6f, 0x75, 0x73, 0x6b, 0x6f, 0x69, 0x2f, 0x72, 0x6f, 0x73, 0x63, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rosco_proto_rawDescOnce sync.Once
	file_rosco_proto_rawDescData = file_rosco_proto_rawDesc
)

func file_rosco_proto_rawDescGZIP() []byte {
	file_rosco_proto_rawDescOnce.Do(func() {
		file_rosco_proto_rawDescData = protoimpl.X.CompressGZIP(file_rosco_proto_rawDescData)
	})
	return file_rosco_proto_rawDescData
}

var file_rosco_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_rosco_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_rosco_proto_goTypes = []any{
	(BusTopic)(0),               // 0: rosco.BusTopic
	(MessageTypeRequest)(0),     // 1: rosco.MessageTypeRequest
	(MessageTypeCommand)(0),     // 2: rosco.MessageTypeCommand
	(ScriptActionType)(0),       // 3: rosco.ScriptActionType
	(*Target)(nil),              // 4: rosco.Target
	(*Config)(nil),              // 5: rosco.Config
	(*ConfigGetRequest)(nil),    // 6: rosco.ConfigGetRequest
	(*ConfigGetResponse)(nil),   // 7: rosco.ConfigGetResponse
	(*OSCValue)(nil),            // 8: rosco.OSCValue
	(*SendMessageRequest)(nil),  // 9: rosco.SendMessageRequest
	(*SendMessageResponse)(nil), // 10: rosco.SendMessageResponse
	(*ConfigSetRequest)(nil),    // 11: rosco.ConfigSetRequest
	(*ConfigSetResponse)(nil),   // 12: rosco.ConfigSetResponse
	(*ScriptAction)(nil),        // 13: rosco.ScriptAction
	(*Script)(nil),              // 14: rosco.Script
	(*ScriptRunRequest)(nil),    // 15: rosco.ScriptRunRequest
	(*ScriptRunResponse)(nil),   // 16: rosco.ScriptRunResponse
	nil,                         // 17: rosco.Config.TargetsEntry
	nil,                         // 18: rosco.Config.ScriptsEntry
}
var file_rosco_proto_depIdxs = []int32{
	17, // 0: rosco.Config.targets:type_name -> rosco.Config.TargetsEntry
	18, // 1: rosco.Config.scripts:type_name -> rosco.Config.ScriptsEntry
	5,  // 2: rosco.ConfigGetResponse.config:type_name -> rosco.Config
	8,  // 3: rosco.SendMessageRequest.values:type_name -> rosco.OSCValue
	5,  // 4: rosco.ConfigSetRequest.config:type_name -> rosco.Config
	5,  // 5: rosco.ConfigSetResponse.config:type_name -> rosco.Config
	3,  // 6: rosco.ScriptAction.type:type_name -> rosco.ScriptActionType
	8,  // 7: rosco.ScriptAction.values:type_name -> rosco.OSCValue
	13, // 8: rosco.Script.actions:type_name -> rosco.ScriptAction
	14, // 9: rosco.ScriptRunRequest.script:type_name -> rosco.Script
	4,  // 10: rosco.Config.TargetsEntry.value:type_name -> rosco.Target
	14, // 11: rosco.Config.ScriptsEntry.value:type_name -> rosco.Script
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_rosco_proto_init() }
func file_rosco_proto_init() {
	if File_rosco_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rosco_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*OSCValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SendMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ScriptAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Script); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ScriptRunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosco_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ScriptRunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rosco_proto_msgTypes[4].OneofWrappers = []any{
		(*OSCValue_Nil)(nil),
		(*OSCValue_Int32)(nil),
		(*OSCValue_Float32)(nil),
		(*OSCValue_String_)(nil),
		(*OSCValue_Blob)(nil),
		(*OSCValue_Int64)(nil),
		(*OSCValue_True)(nil),
		(*OSCValue_False)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rosco_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rosco_proto_goTypes,
		DependencyIndexes: file_rosco_proto_depIdxs,
		EnumInfos:         file_rosco_proto_enumTypes,
		MessageInfos:      file_rosco_proto_msgTypes,
	}.Build()
	File_rosco_proto = out.File
	file_rosco_proto_rawDesc = nil
	file_rosco_proto_goTypes = nil
	file_rosco_proto_depIdxs = nil
}
